// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/comments": {
            "get": {
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "comments"
                ],
                "summary": "Get comments (HTML page)",
                "parameters": [
                    {
                        "type": "string",
                        "default": "0",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "sortFromNew",
                            "sortFromOldest"
                        ],
                        "type": "string",
                        "default": "sortFromNew",
                        "description": "Sort order: 'sortFromOldest' or 'sortFromNew'",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "HTML page with comments",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to load comments",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "comments"
                ],
                "summary": "Create a new comment (via form)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comment text",
                        "name": "text",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "303": {
                        "description": "Redirect to /comments",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Текст комментария обязателен",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Не удалось сохранить комментарий",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "comments"
                ],
                "summary": "Update a comment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comment ID to update",
                        "name": "commentID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "New comment text",
                        "name": "text",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "303": {
                        "description": "Redirect to /comments",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Текст или ID комментария обязателен",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Комментарий не найден",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Не удалось обновить комментарий",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Comment Service API",
	Description:      "HTML-based comment management API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
